image: php:latest

# cache:
#   paths:
#     - vendor/

before_script:
  - apt-get update
  # - apt-get update -yqq
#   # Install & enable Xdebug for code coverage reports
#   - pecl install xdebug
#   - docker-php-ext-enable xdebug
#   - apt-get install -yqq git libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
#   # Install PHP extensions
#   - docker-php-ext-install mbstring pdo_pgsql curl intl gd xml zip bz2 opcache

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: 
  image: npm:latest
  script:
    - echo "Triggered build from pipeline..."
    - cd next-js/
    - npm i
    - npm run build
    - echo "App build complete."

app-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - apt-get update
    - npm install pm2@latest -g
  script:
    - cd next-js/
    - echo "Triggered unit test stage from pipeline..."
    - pm2 start pages/index.js
    - pm2 list
    - echo "Next.js app tests complete.... Cleaning up and stopping tests"
    - pm2 stop pages/index.js
    - echo "Cleanup completed."

deploy-job:
  stage: deploy
  environment: production
  image: debian:bookworm-20240110
  before_script:
    - 'command -v ssh-agent >/dev/null || (apt-get update -y && apt-get install openssh-client -y rsync)'
    - apt-get update
    - apt-get install -y git
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying application to Team9 socs VM..."
    - rsync -avz --delete --exclude='.git/' --exclude='.gitlab-ci.yml' --no-t --no-perms ./ socs@cis4250w24-09.socs.uoguelph.ca:/var/www/html/team_9
    - echo "Application simulation successfully deployed to socs."
  only:
    - main
